library("GO.db")
library("annotate")
library("genefilter")
library("GOstats")
library(org.Sc.sgd.db)
library("RamiGO")

goIDs <- c("GO:0019912")
color <- c("red")
dd <- getAmigoTree(goIDs=goIDs,color=color,filename="example",picType="dot",saveResult=FALSE)
tt <- readAmigoDot(object=dd)
write.table(tt@annot[,1:6],file='/tmp/R/test_bbb.txt',quote=FALSE,sep = "\t",row.names=FALSE,col.names=FALSE)
write.table(tt@relations[,1:2],file="/tmp/R/test_aaa.txt",quote=FALSE,sep = "\t",row.names=TRUE,col.names=FALSE)
cat('aaaaaa')