#setwd("/var/www/SGA/R_results/GO_enrichment_test/")
#jpeg("my.jpg")
#source("http://bioconductor.org/biocLite.R")
#biocLite("gplots")
#postscript("plot1.eps", horizontal=FALSE, onefile=FALSE,height=8, width=6, pointsize=10)
library()
#getwd()
png("/var/www/SGA/R_results/GO_enrichment_test/my22.png")
plot(1:10)
dev.off()
nowtime<-as.integer( Sys.time())
cat(nowtime)
#dev.list()